<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>xyz.wewin.autumn</groupId>
		<artifactId>autumn-gateway</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>autumn-gateway-starters</artifactId>
	<packaging>pom</packaging>

	<modules>

		<module>limit-autumn-gateway</module>
		<module>limit-autumn-gateway-starter</module>
		<module>limit-autumn-gateway-starter-using</module>
	</modules>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>25</java.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>xyz.wewin.autumn</groupId>
				<artifactId>limit-autumn-gateway</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>xyz.wewin.autumn</groupId>
				<artifactId>limit-autumn-gateway-starter</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
