spring.application.name=autumn-gateway-examples-basic
server.port=8080

spring.cloud.consul.discovery.register=false
# 路由ID
spring.cloud.gateway.server.webflux.routes[0].id=user-route
# 目标URI
spring.cloud.gateway.server.webflux.routes[0].uri=http://127.0.0.1:8081
# Predicates（断言）
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
# Filters（过滤器）
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1