spring.application.name=autumn-gateway
server.port=${PORT:8085}
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n
spring.redis.host=localhost
spring.redis.port=6379
spring.output.ansi.enabled=ALWAYS

# Route: account-service
spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=http://localhost:8091
spring.cloud.gateway.routes[0].predicates[0]=Path=/account/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/account/(?<path>.*), /$\{path}
spring.cloud.gateway.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=20

# Route: customer-service
spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=http://localhost:8092
spring.cloud.gateway.routes[1].predicates[0]=Path=/customer/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/customer/(?<path>.*), /$\{path}

# Route: order-service
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://localhost:8090
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/order/(?<path>.*), /$\{path}

# Route: product-service
spring.cloud.gateway.routes[3].id=product-service
spring.cloud.gateway.routes[3].uri=http://localhost:8093
spring.cloud.gateway.routes[3].predicates[0]=Path=/product/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/product/(?<path>.*), /$\{path}