spring.application.name=autumn-gateway-examples-consul-config
server.port=8080
# 家中树莓派的Docker中的Consul实例
spring.cloud.consul.host=192.168.1.16
spring.cloud.consul.port=8500

# ========== Consul Config（新增）==========
# 关键：开启 config import，Boot 4.1 的外部化配置入口
# 这会选择仅加载 和 的配置。/contextone和/context/two
# spring.config.import=optional:consul:myhost:8500/contextone;/context/two
spring.config.import=consul:
# KV 前缀 & 共享 context（默认就是 config，可省）
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.default-context=application
spring.cloud.consul.config.fail-fast=false

# 动态刷新（你砍了 actuator，靠这个）
spring.cloud.consul.config.watch.enabled=true
#spring.cloud.consul.config.refresh-interval=10
spring.cloud.consul.config.read-timeout=3600
spring.cloud.consul.config.watch.wait-time=5
# 默认是毫秒
spring.cloud.consul.config.watch.delay=10000


# 如果 Consul 开了 ACL（推荐生产），配 token
# spring.cloud.consul.config.acl-token=${CONSUL_HTTP_TOKEN}
# spring.cloud.consul.token=${CONSUL_HTTP_TOKEN}   # discovery 也用同一个


spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=3s
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

# 玩法 A：discovery.locator.enabled=true（最快）=> GET http://localhost:8080/user-service/api/users/1
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# 关 Weight filter（SCG 5.x 的 property，默认 true）
spring.cloud.gateway.filter.weight.enabled=false
spring.cloud.gateway.server.webflux.filter.weight.enabled=false
# 路由ID
spring.cloud.gateway.server.webflux.routes[0].id=service-a
# 目标URI
spring.cloud.gateway.server.webflux.routes[0].uri=lb://service-a
# Predicates（断言）
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
# Filters（过滤器）
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1