spring.application.name=dubbo-a
server.port=8083


# ===== Dubbo 基础配置 =====
dubbo.application.name=dubbo-a
dubbo.application.qos-enable=false

# ===== 双协议：dubbo 和 rest =====
# 协议 0：dubbo（TCP）
dubbo.protocols[0].name=dubbo
dubbo.protocols[0].port=20880

# 协议 1：rest（HTTP，Spring MVC）
dubbo.protocols[1].name=rest
dubbo.protocols[1].port=8090
#dubbo.protocols[1].server=netty4
dubbo.protocols[1].server=jetty

# ===== 注册中心：Consul（移除 Zookeeper）=====
dubbo.registry.address=consul://192.168.1.16:8500
# 可选：Consul 数据中心
dubbo.registry.parameters.data-center=dc1

# ===== 包扫描（@DubboService 所在包）=====
dubbo.scan.base-packages=xyz.wewin.autumn.gateway.examples.dubbo
logging.level.org.apache.dubbo.common.extension=DEBUG
logging.level.org.apache.dubbo.config=DEBUG
