spring.application.name=autumn-gateway-examples-consul
server.port=8080
# 家中树莓派的Docker中的Consul实例
spring.cloud.consul.host=192.168.1.16
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=3s
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

# 玩法 A：discovery.locator.enabled=true（最快）=> GET http://localhost:8080/user-service/api/users/1
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# 路由ID
spring.cloud.gateway.server.webflux.routes[0].id=user-service
# 目标URI
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
# Predicates（断言）
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
# Filters（过滤器）
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1