<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>xyz.wewin.autumn</groupId>
        <artifactId>autumn-gateway-starters</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>config-discovery-autumn-gateway-starter-using</artifactId>
    <name>config-discovery-autumn-gateway-starter-using</name>
    <description>config-discovery-autumn-gateway-starter 使用示例</description>

    <properties>
        <start-class>xyz.wewin.autumn.gateway.config.discovery.using.ConfigDiscoveryAutumnGatewayStarterUsingApplication</start-class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>xyz.wewin.autumn</groupId>
            <artifactId>config-discovery-autumn-gateway-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway-server-webflux</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
